[build]
builder = "DOCKERFILE"
dockerfilePath = "Encadri-Backend/Encadri-Backend/Dockerfile"

[deploy]
startCommand = "dotnet Encadri-Backend.dll"
healthcheckPath = "/swagger/index.html"
healthcheckTimeout = 300
